package writory.domain.user.exception

class UserNotFoundException : RuntimeException()
