package writory.service.dashboard.exception

class UserFoundException : RuntimeException()
